apiVersion: v1
kind: PersistentVolume
metadata:
  name: ce-lab34-data
spec:
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ce-lab34-local
  local:
    path: /var/local/ce-lab34-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lab34-worker
