apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: ce-lab15-pods
webhooks:
- name: pods.ce-lab15.example.com
  admissionReviewVersions: [v1]
  sideEffects: None
  failurePolicy: Fail
  timeoutSeconds: 5
  namespaceSelector:
    matchLabels:
      ce-lab15: scoped
  rules:
  - apiGroups: ['']
    apiVersions: [v1]
    operations: [CREATE]
    resources: [pods]
    scope: Namespaced
  clientConfig:
    service:
      name: admission
      namespace: ce-lab15-system
      path: /validate
      port: 443
    caBundle: CA_BUNDLE_PLACEHOLDER
