apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: policy-web
  template:
    metadata:
      labels:
        app: policy-web
        owner: platform-team
    spec:
      terminationGracePeriodSeconds: 2
      containers:
      - name: web
        image: python:3.12-slim
        command:
        - python
        - -u
        - -m
        - http.server
        - '8080'
        resources:
          requests:
            cpu: 20m
            memory: 16Mi
          limits:
            memory: 128Mi
