apiVersion: v1
kind: Pod
metadata:
  name: goldpinger-slow
  labels:
    app: goldpinger
    experiment: lab11
spec:
  serviceAccountName: goldpinger
  containers:
  - name: goldpinger
    image: bloomberg/goldpinger:3.11.3
    env:
    - name: HOST
      value: 0.0.0.0
    - name: PORT
      value: '9090'
    - name: CLIENT_PORT_OVERRIDE
      value: '8080'
    - name: PING_TIMEOUT
      value: 300ms
    - name: REFRESH_INTERVAL
      value: '2'
    - name: NAMESPACE
      value: chaos-labs
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    ports:
    - containerPort: 9090
  - name: toxiproxy
    image: ghcr.io/shopify/toxiproxy:2.12.0
    args:
    - -host=0.0.0.0
    ports:
    - containerPort: 8474
    - containerPort: 8080
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      timeoutSeconds: 1
      periodSeconds: 2
      failureThreshold: 2
