apiVersion: v1
kind: LimitRange
metadata:
  name: container-budget
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 100m
      memory: 16Mi
    default:
      cpu: 200m
      memory: 64Mi
    max:
      cpu: 200m
      memory: 64Mi
