apiVersion: v1
kind: ServiceAccount
metadata:
  name: builder
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-reader
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: role-writer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-creator
rules:
- apiGroups: [""]
  resources: [pods]
  verbs: [create, get, list, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-lister
rules:
- apiGroups: [""]
  resources: [secrets]
  verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-author
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: [roles, rolebindings]
  verbs: [create, get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: builder-creates-pods
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: Role, name: pod-creator}
subjects:
- {kind: ServiceAccount, name: builder, namespace: ce-lab22}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reader-lists-secrets
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: Role, name: secret-lister}
subjects:
- {kind: ServiceAccount, name: secret-reader, namespace: ce-lab22}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: writer-authors-roles
roleRef: {apiGroup: rbac.authorization.k8s.io, kind: Role, name: role-author}
subjects:
- {kind: ServiceAccount, name: role-writer, namespace: ce-lab22}
