apiVersion: authorization.k8s.io/v1
kind: SubjectAccessReview
metadata: {}
spec:
  user: system:serviceaccount:ce-lab32:builder
  resourceAttributes: {namespace: ce-lab32, verb: create, resource: pods, subresource: exec}
